services:
  - type: web
    name: goal-breaker-backend
    runtime: docker
    region: frankfurt
    rootDir: backend

    plan: starter

    autoDeploy: true
    healthCheckPath: /

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: PORT
        value: 8000

      - key: BACKEND_CORS_ORIGINS
        fromService:
          type: web
          name: goal-breaker-frontend
          property: url

      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: goal-breaker-frontend
    runtime: docker
    region: frankfurt
    rootDir: frontend

    plan: starter

    autoDeploy: true
    healthCheckPath: /api/keep-alive

    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: goal-breaker-backend
          property: url

      - key: DATABASE_URL
        sync: false

      - key: BETTER_AUTH_SECRET
        sync: false

      - key: BETTER_AUTH_URL
        value: https://goal-breaker-frontend.onrender.com

      - key: NEXT_PUBLIC_BETTER_AUTH_URL
        value: https://goal-breaker-frontend.onrender.com

      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
